{% set version = '0.1.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gginnards
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gginnards_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gginnards/gginnards_{{ version }}.tar.gz
  sha256: 5c2d61936fefee5fef00a9a8eb33a470404fa0a134079944ee9bfbb8085c9cfc

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ggplot2 >=3.3.1
    - r-magrittr >=1.5
    - r-rlang >=0.4.0
    - r-stringr >=1.4.0
    - r-tibble >=2.1.0
  run:
    - r-base
    - r-ggplot2 >=3.3.1
    - r-magrittr >=1.5
    - r-rlang >=0.4.0
    - r-stringr >=1.4.0
    - r-tibble >=2.1.0

test:
  commands:
    - $R -e "library('gginnards')"           # [not win]
    - "\"%R%\" -e \"library('gginnards')\""  # [win]

about:
  home: https://www.r4photobiology.info, https://github.com/aphalo/gginnards
  license: GPL-2.0-or-later
  summary: 'Extensions to ''ggplot2'' providing low-level debug tools: statistics and geometries
    echoing their data argument. Layer manipulation: deletion, insertion, extraction
    and reordering of layers. Deletion of unused variables from the data object embedded
    in "ggplot" objects.'
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - RJMW

# Package: gginnards
# Type: Package
# Title: Explore the Innards of 'ggplot2' Objects
# Version: 0.1.2
# Date: 2023-05-24
# Authors@R: c( person("Pedro J.", "Aphalo", email = "pedro.aphalo@helsinki.fi", role = c("aut", "cre"), comment = c(ORCID = "0000-0003-3385-972X"))    )
# Maintainer: Pedro J. Aphalo <pedro.aphalo@helsinki.fi>
# Description: Extensions to 'ggplot2' providing low-level debug tools: statistics and geometries echoing their data argument. Layer manipulation: deletion, insertion, extraction and reordering of layers. Deletion of unused variables from the data object embedded in "ggplot" objects.
# License: GPL (>= 2)
# LazyLoad: TRUE
# ByteCompile: TRUE
# Depends: R (>= 3.6.0), ggplot2 (>= 3.3.1)
# Imports: utils, methods, rlang (>= 0.4.0), stringr (>= 1.4.0), magrittr (>= 1.5), tibble (>= 2.1.0)
# Suggests: knitr (>= 1.24), rmarkdown (>= 1.14), sf (>= 0.9), pryr (>= 0.1.4)
# URL: https://www.r4photobiology.info, https://github.com/aphalo/gginnards
# BugReports: https://github.com/aphalo/gginnards/issues
# Encoding: UTF-8
# RoxygenNote: 7.2.3
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2023-05-24 19:18:13 UTC; aphalo_2
# Author: Pedro J. Aphalo [aut, cre] (<https://orcid.org/0000-0003-3385-972X>)
# Repository: CRAN
# Date/Publication: 2023-05-24 20:10:02 UTC
